frontend/bonsai_app/blueprints/login/__init__.py
"""Login blueprint."""

from .views import login_bp

frontend/bonsai_app/blueprints/login/views.py
"""Manage user authentication."""

import logging

from flask import (Blueprint, Response, flash, redirect, render_template,
                   request, session, url_for)
from flask_login import UserMixin, login_required, login_user, logout_user
from requests.exceptions import HTTPError

from ... import __version__ as VERSION
from ...bonsai import TokenObject, get_auth_token, get_current_user
from ...extensions import login_manager

LOG = logging.getLogger(__name__)

login_bp = Blueprint(
    "login",
    __name__,
    template_folder="templates",
    static_folder="static",
    static_url_path="/login",
)


class LoginUser(UserMixin):
    """Container for user data and perform login."""

    def __init__(self, user_data, token_data):
        """Create a new user object."""
        self.roles = []
        for key, value in user_data.items():
            setattr(self, key, value)
        # store token
        self.token = token_data

    def get_id(self):
        """Get user auth token"""
        return self.token.dict()

    @property
    def is_admin(self):
        """Check if the user is admin."""
        return "admin" in self.roles


@login_bp.route("/login")
def login_page():
    """Landing page view."""
    return render_template("login.html", title="Login", version=VERSION)


@login_bp.route("/logout")
@login_required
def logout():
    """Logout user."""
    logout_user()
    session.pop("email", None)
    session.pop("fname", None)
    session.pop("lname", None)
    session.pop("locale", None)
    return redirect(url_for("public.index"))


@login_bp.route("/login", methods=["GET", "POST"])
def login():
    """Login a user."""
    if "next" in request.args:
        session["next_url"] = request.args["next"]

    # get login credentials from form
    username = request.form["username"]
    password = request.form["password"]

    try:
        token_obj: TokenObject = get_auth_token(username, password)
    except HTTPError as err:
        # if invalid credentials
        if err.response.status_code == 401:
            flash("Invalid login credentials", "danger")
        else:
            flash("Sorry, you could not log in due to an internal error", "warning")

        return redirect(url_for("public.index"))

    user_obj = get_current_user(token_obj)
    user = LoginUser(user_obj, token_obj)
    return perform_login(user)


@login_manager.user_loader
def load_user(user_id):
    """Reload user object from user id stored in session."""
    token = TokenObject(**user_id)
    try:
        user_obj = get_current_user(token)
    except HTTPError:
        return None

    user = LoginUser(user_obj, token) if user_obj else None
    return user


def perform_login(user: LoginUser) -> Response:
    """Login user.

    :param user: User
    :type user: LoginUser
    :return: redirect user to /groups if login is successfull
    :rtype: Response
    """
    LOG.error(
        [redirect(url_for("public.index")), type(redirect(url_for("public.index")))]
    )
    if login_user(user):
        next_url = session.pop("next_url", None)
        return redirect(
            request.args.get("next") or next_url or url_for("groups.groups")
        )

    # could not log in
    flash("sorry, you could not log in", "warning")
    LOG.warning("User authentication failed.")
    return redirect(url_for("public.index"))


@login_manager.unauthorized_handler
def unauthorized_handler() -> Response:
    """Define function for handeling unauthorized users.

    :return: redirect failed auth attempt to login page
    :rtype: Response
    """
    return redirect(url_for("login.login_page"))

frontend/bonsai_app/blueprints/login/templates/login.html
{% extends "bootstrap_base.html" %}

{% block css %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('login.static', filename='login.css')}}">
{% endblock css %}

{% block content %}
<div class="w-100">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% set category = "border-" + messages[-1][0] %}
    {% else %}
        {% set category = "" %}
    {% endif %}
    <div class="row vh-100">
        <div class="d-none d-xl-block col-xl-3 login-gradient-upper">
            <h1 class="text-white sw-logo-text sw-logo-text-lg fw-bold text-center pt-5">Bonsai</h1>
            <div class="login-gradient-lower overflow-hidden"></div>
            <p class="text-white fs-4 fw-bold text-center position-relative top-50 start-0">Version {{version}}</p>
        </div>
        <div class="col-12 col-xl-9 bg-white container px-5">
            <div class="w-50 mx-auto">
                <div class="row pt-5 align-items-center">
                    <form action="{{ url_for('login.login') }}" method="POST" name="login">
                        <div class="col-lg-6">
                            <h1>Welcome! Log in</h1>
                        </div>
                        <div class="col-lg-auto mt-2">
                            <input class="form-control form-control-lg rounded-1" type="text" placeholder="User name" id="username" name="username" data-test-id="username-input">
                        </div>
                        <div class="col-lg-auto mt-4">
                            <input class="form-control form-control-lg rounded-1" type="password" placeholder="Password" id="password" name="password" data-test-id="password-input">
                        </div>
                        <div class="col-lg-auto mt-4">
                            <button class="btn btn-dark btn-lg rounded-1 w-100" type="submit" data-test-id="login-btn">Login</button>
                        </div>
                        <div class="col-lg-auto mt-2">
                            <button class="btn btn-outline-dark btn-lg rounded-1 w-100" type="submit">Request an account</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% if messages %}
        {% set category = messages[-1][0] %}
        {% set message = messages[-1][1] %}
        <p class="text-{{category}} fs-6 fw-bold">{{ message }}</p>
    {% endif %}
    {% endwith %}
</div>
{% endblock content %}