frontend/bonsai_app/blueprints/admin/__init__.py
"""Admin related blueprints."""

from .views import admin_bp

frontend/bonsai_app/blueprints/admin/views.py
"""Declaration of flask admin views"""

from flask import (Blueprint, current_app, flash, redirect, render_template,
                   request, url_for)
from flask_login import current_user, login_required
from requests.exceptions import HTTPError
from wtforms import (Form, PasswordField, SelectMultipleField, StringField,
                     ValidationError, validators, widgets)

from ...bonsai import TokenObject
from ...bonsai import create_user as create_new_user
from ...bonsai import delete_user as delete_user_from_db
from ...bonsai import get_user, get_users
from ...bonsai import update_user as update_user_info

admin_bp = Blueprint(
    "admin",
    __name__,
    template_folder="templates",
    static_folder="static",
    static_url_path="/admin/static",
)


@admin_bp.route("/admin")
@login_required
def admin_panel():
    """Default admin panel view."""
    # if not valid token
    if not current_user.is_admin:
        flash("You dont have permission to view this page", "warning")
        return redirect(url_for("public.home"))

    return redirect(url_for("admin.view_users"))


@admin_bp.route("/admin/users")
@login_required
def view_users():
    """Edit Bonsai users."""
    # if not valid token
    if not current_user.is_admin:
        flash("You dont have permission to view this page", "warning")
        return redirect(url_for("public.home"))

    token = TokenObject(**current_user.get_id())
    # get all users
    users = get_users(token)
    return render_template("users_list.html", users=users)


PASSWORD_VALIDATORS = [
    validators.Length(min=8, max=72),
    validators.Regexp(
        r"^((?=\S*?[A-Z])(?=\S*?[a-z])(?=\S*?[0-9]).+)\S$",
        message="The password must include upper- and lower case letters with at leats one number.",
    ),
    validators.EqualTo("confirm", message="Passwords must match"),
]


class MultiCheckboxField(SelectMultipleField):  # pylint: disable=too-few-public-methods
    """WTforms MultiCheckboxField."""

    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()


class UserInfoForm(Form):
    """Register a new user."""

    username = StringField("Username", [validators.Length(min=4, max=25)])
    first_name = StringField("First name", [validators.Length(min=2, max=50)])
    last_name = StringField("Last name", [validators.Length(min=2, max=50)])
    email = StringField("Email Address", [validators.Email()])
    password = PasswordField("Password", [validators.Optional(), *PASSWORD_VALIDATORS])

    confirm = PasswordField("Repeat Password")
    roles = MultiCheckboxField("Roles", choices=["admin", "user", "uploader"])

    def validate_roles(form, field):
        """Validate that one or more roles is selected."""
        if field.data is None or len(field.data) == 0:
            raise ValidationError("At least one role must be selected")


class UserRegistrationForm(UserInfoForm):  # pylint: disable=too-few-public-methods
    """Form for registering a new user."""

    password = PasswordField("Password", PASSWORD_VALIDATORS)

    def validate_username(form, field):
        """Check if username already exists."""
        username = field.data
        token = TokenObject(**current_user.get_id())
        user_exists = True
        try:
            get_user(token, username=username)
        except HTTPError as error:
            if error.response.status_code == 404:
                user_exists = False
            else:
                raise error
        if user_exists:
            raise ValidationError(f"An user with username {username} already exists")


@admin_bp.route("/admin/users/new", methods=["GET", "POST"])
@login_required
def create_user():
    """Create new users."""
    # if not valid token
    if not current_user.is_admin:
        flash("You dont have permission to view this page", "warning")
        return redirect(url_for("public.home"))

    form = UserRegistrationForm(request.form)
    if request.method == "POST" and form.validate():
        token = TokenObject(**current_user.get_id())
        try:
            status = create_new_user(token, user_obj=form.data)
        except HTTPError as error:
            flash(
                f"Error when creating a new user, {error.response.status_code}",
                "warning",
            )
        else:
            flash("Created new user", "success")
        return redirect(url_for("admin.view_users"))
    # get all users
    return render_template("user_form.html", method="create", form=form)


@admin_bp.route("/admin/users/delete", methods=["POST"])
@login_required
def delete_users():
    """Delete users."""
    # if not valid token
    if not current_user.is_admin:
        flash("You dont have permission to view this page", "warning")
        return redirect(url_for("public.home"))

    token = TokenObject(**current_user.get_id())
    removed_users = []
    for username, value in request.form.items():
        if value == "on":
            try:
                delete_user_from_db(token, username=username)
            except Exception as error:
                flash(f"Error when deleting user: {username}", "danger")
                raise ValueError(error) from error
            removed_users.append(username)

    # inform user which samples was removed
    if len(removed_users) > 0:
        names = ", ".join(removed_users)
        flash(f"Deleted users: {names}", "success")
    # get all users
    return redirect(request.referrer)


@admin_bp.route("/admin/users/<username>", methods=["GET", "POST"])
@login_required
def update_user(username):
    """Edit existing user."""
    # if not valid token
    if not current_user.is_admin:
        flash("You dont have permission to view this page", "warning")
        return redirect(url_for("public.home"))

    token = TokenObject(**current_user.get_id())
    # get all users
    user = get_user(token, username=username)
    form = UserInfoForm(request.form)

    if request.method == "POST":
        if not form.validate():
            flash("Invalid input data", "warning")
        elif "update" in request.form:
            try:
                update_user_info(token, username=username, user=form.data)
            except Exception as error:
                flash("An error occurred when updating user info", "warning")
                current_app.logger.error("Error updating user: %s", str(error))
            else:
                flash(f"Updated user {username}", "success")
                current_app.logger.debug("Updated user: %s", username)
        else:
            try:
                delete_user_from_db(token, username=username)
            except:
                flash(f"An error occurred when removing {username}", "warning")
            else:
                flash(f"Removed user {username}", "success")
    elif request.method == "GET":
        # populate form with deafults from the database
        form.username.data = user["username"]
        form.first_name.data = user["first_name"]
        form.last_name.data = user["last_name"]
        form.email.data = user["email"]
        form.roles.data = user["roles"]
        if current_user.authentication_method == "ldap":
            form.password.render_kw = {"disabled": True}
            form.confirm.render_kw = {"disabled": True}
            flash(
                f"Passwords are managed by the {current_user.authentication_method} server",
                "info",
            )

    # get all users
    return render_template("user_form.html", method="edit", form=form)

frontend/bonsai_app/blueprints/admin/templates/admin_panel.html
{% extends "admin_panel_base.html" %}

{% block css %}
{{ super() }}
{% endblock css %}

{% block admin_panel_content %}
<div class="container-fluid">
    <h4>Placeholder</h4>
</div>
{% endblock admin_panel_content %}

frontend/bonsai_app/blueprints/admin/templates/admin_panel_base.html
{% extends "layout.html" %}

{% block title %}
    Bonsai - Admin Panel
{% endblock title %}

{% block css %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('admin.static', filename='admin.css')}}">
{% endblock css %}

{% block content %}
<div class="container-fluid br-layout">
    <aside class="br-sidebar border-end pe-2">
        <h6 class="sidebar-heading mt-4 mb-1 text-muted text-uppercase">Edit</h6>
        <ul class="nav flex-column">
            <li class="nav-item mb-2" disabled>
                <a class="link-secondary"
                    href={{ url_for('groups.edit_groups') }}>
                    <i class="bi bi-collection"></i>
                    Groups
                </a>
            </li>
            <li class="nav-item mb-2">
                <a class="link-secondary" href={{ url_for('admin.view_users') }}>
                    <i class="bi bi-people"></i>
                    Users
                </a>
            </li>
        </ul>
    </aside>
    <main class="br-main order-1">
        {% block admin_panel_content %}
        {% endblock admin_panel_content %}
    </main>
</div>
{% endblock content %}

frontend/bonsai_app/blueprints/admin/templates/user_form.html
{% extends "admin_panel_base.html" %}
{% set text_field_types = 'DateField', 'DateTimeField', 'DecimalField', 'FloatField', 'IntegerField', 'PasswordField', 'SelectField', 'SelectMultipleField', 'StringField', 'TextAreaField', 'TextField' %}
{% set other_field_types = 'BooleanField', 'MultiCheckboxField', 'FileField', 'RadioField', 'SubmitField' %}


{% block css %}
{{ super() }}
{% endblock css %}

{% block admin_panel_content %}
<div class="container-fluid">
    {% if method == "create" %}
        <h2 class="pt-2">Create user</h2>
        <hr class="mt-2 mb-0 col-md-3 border border-success border-2">
        <p>Create a new user with the selected user roles.</p>
    {% else %}
        <h2 class="pt-2">Update: {{ form.username.data }}</h2>
        <hr class="mt-2 mb-0 col-md-3 border border-success border-2">
        <p>Edit the user credentials or roles.</p>
    {% endif %}
    <div class="card col-md-10">
        <div class="card-body user-form">
            {% if method == "create" %}
                {% set action_url=url_for("admin.create_user") %}
            {% else %}
                {% set action_url=url_for("admin.update_user", username=form.username.data) %}
            {% endif %}
            <form class="form" action={{ action_url }} method="post">
                <div class="row g-1">
                    <div class="col-md">
                        {{ bootstrap_field(form.first_name) }}
                    </div>
                    <div class="col-md">
                        {{ bootstrap_field(form.last_name) }}
                    </div>
                </div>
                <div class="row pt-2 g-3">
                    <div class="col-md">
                        {{ bootstrap_field(form.email) }}
                    </div>
                </div>
                <div class="row pt-2 g-3">
                    <div class="col-md">
                        {{ bootstrap_field(form.username) }}
                    </div>
                </div>
                <div class="row pt-4 g-3">
                    <div class="col-md">
                        {{ bootstrap_field(form.password) }}
                    </div>
                </div>
                <div class="row pt-1 g-3">
                    <div class="col-md">
                        {{ bootstrap_field(form.confirm) }}
                    </div>
                </div>
                <h5 class="card-title pt-2">Roles</h5>
                {{ form.roles }}
                <div class="row g-2 mt-2">
                {% if method == "create" %}
                    <button  class="btn mt-2 btn-success">
                            <i class="bi bi-person-fill-add"></i>
                            Create
                    </button>
               {% else %}
                    <div class="col-auto">
                        <button class="btn btn-warning" type="submit" name="update">
                            <i class="bi bi-person-fill-up"></i>
                            Update
                        </button>
                    </div>
                    <div class="col-auto">
                        <button class="btn btn-danger" type="submit" name="delete">
                            <i class="bi bi-person-fill-x"></i>
                            Delete
                        </button>
                    </div>
                {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock admin_panel_content %}

{% macro bootstrap_field(field, form_group=True, placeholder=True, label=True, errors=True, horizontal=False) %}

    {% set class_value = False %}
    {%- if field.type in text_field_types -%}
        {% set class_value = 'form-control' %}
    {%- elif field.type == 'SubmitField' -%}
        {% set class_value = 'btn btn-default' %}
    {%- endif -%}

    {% set placeholder_value = False %}
    {%- if placeholder and field.type in text_field_types -%}
        {% set placeholder_value = field.label.text %}
    {%- endif -%}

    {%- if label -%}
        {% if horizontal -%}
            {% set field_label = field.label(class_='col-sm-2 control-label') %}
        {%- else -%}
            {% set field_label = field.label(class_='control-label') %}
        {%- endif %}
    {%- endif -%}

    {% set field_output = field(class_=class_value, placeholder=placeholder_value) %}

    {%- if horizontal %}
        {%- if field.errors -%}
             {% set field_output = field_output + '<span class="bi bi-remove form-control-feedback" aria-hidden="true"></span><span class="sr-only">(error)</span>' %}
        {%- endif %}

        {%- if field.type not in ['SubmitField', 'BooleanField'] -%}
            {% set field_output = '<div class="col-sm-10">%s</div>' % field_output %}
        {%- endif %}
    {%- endif -%}

    {%- if field.type == 'BooleanField' -%}
        {% set field_output = '<div class="checkbox"><label>%s %s</label></div>' % (field_output, field.label.text) %}
    {%- elif field.type != 'SubmitField' and label -%}
        {% set field_output = field_label + field_output %}
    {%- endif -%}

    {% if horizontal -%}
        {% if field.type in ['SubmitField', 'BooleanField'] -%}
            {% set field_output = '<div class="col-sm-offset-2 col-sm-10">%s</div>' % field_output %}
        {%- endif %}
    {%- endif -%}

    {% set form_group_classes = 'form-group' %}
    {%- if field.errors -%}
        {% set form_group_classes = form_group_classes + ' is-invalid' %}
    {%- endif -%}

    {%- if field.flags.required -%}
        {% set form_group_classes = form_group_classes + ' required' %}
    {%- endif -%}

    {%- if form_group -%}
        {% set field_output = '<div class="%s">%s</div>' % (form_group_classes, field_output) %}
    {%- endif -%}

    {%- if field.type == 'HiddenField' -%}
        {{ field }}
    {%- else -%}
        {{ field_output|safe }}

        {%- if field.description -%}
            {% if horizontal -%}
                <div class="col-sm-10 col-sm-offset-2">
            {%- endif -%}
            <p class="help-block">{{ field.description }}</p>
            {%- if horizontal -%}
                </div>
            {%- endif -%}
        {%- endif %}

        {%- if field.errors and errors -%}
            {% if horizontal -%}
                <div class="col-sm-10 col-sm-offset-2">
            {% endif %}
            {%- if field.errors|count == 1 -%}
                <div class="invalid-feedback">{{ field.errors[0] }}</div>
            {%- else -%}
                <ul>
                {%- for error in field.errors -%}
                    <li class="invalid-feedback">{{ error }}</li>
                {%- endfor -%}
                </ul>
            {%- endif %}
            {%- if horizontal -%}
                </div>
            {%- endif %}
        {%- endif -%}
    {%- endif -%}
{%- endmacro %}

frontend/bonsai_app/blueprints/admin/templates/users_list.html
{% extends "admin_panel_base.html" %}

{% block css %}
{{ super() }}
{% endblock css %}

{% block admin_panel_content %}
<div class="container-fluid">
    <h2 class="pt-2">Manage users</h2>
    <form action={{ url_for("admin.delete_users") }} method="post">
        <div class="pt-2">
            <a  class="btn btn-outline-success" href={{ url_for("admin.create_user") }}>
                <i class="bi bi-person-fill-add"></i>
                Create user
            </a>
            <button class="btn btn-outline-danger" type="submit">
                <i class="bi bi-person-fill-x"></i>
                Delete users
            </button>
        </div>
        <table class="table table-hover">
            <thead>
                <th></th>
                <th>Username</th>
                <th>Name</th>
                <th>Email</th>
                <th>Roles</th>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td><input type="checkbox" name="{{ user.username }}"></td>
                    <td>
                        <a class="text-success" href={{ url_for("admin.update_user", username=user.username) }}>
                            {{ user.username }}
                        </a>
                    </td>
                    <td>
                        {% if user.first_name == "" or user.first_name == None %}
                        -
                        {% else %}
                        {{ user.first_name }} {{ user.last_name }}
                        {% endif %}
                    </td>
                    <td><a href="mailto:{{ user.email }}">{{ user.email }}</a></td>
                    <td>
                        {% for role in user.roles %}
                            {{ role }}
                            <br>
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </form>
</div>
{% endblock admin_panel_content %}