frontend/bonsai_app/blueprints/sample/views.py
"""Declaration of views for samples"""

import json
import logging
from datetime import date
from itertools import groupby
from typing import Any, Dict, Tuple

from flask import (Blueprint, abort, current_app, flash, make_response,
                   redirect, render_template, request, url_for)
from flask_login import current_user, login_required
from requests import HTTPError

from ...bonsai import (
    TokenObject,
    cgmlst_cluster_samples,
    delete_samples,
    find_samples_similar_to_reference,
    get_antibiotics,
    get_group_by_id,
    get_lims_export_response,
    get_sample_by_id,
    get_variant_rejection_reasons,
    post_comment_to_sample,
    remove_comment_from_sample,
    update_sample_qc_classification,
    update_variant_info,
)
from ...models import BadSampleQualityAction, QualityControlResult
from .controllers import (filter_variants, filter_variants_if_processed,
                          get_all_variant_types, get_all_who_classifications,
                          get_variant_genes, kw_metadata_to_table,
                          sort_variants, split_metadata)

LOG = logging.getLogger(__name__)

samples_bp = Blueprint(
    "samples",
    __name__,
    template_folder="templates",
    static_folder="static",
    static_url_path="/samples/static",
)


@samples_bp.route("/samples")
@login_required
def samples():
    """Samples view."""
    return render_template("samples.html")


@samples_bp.route("/samples/remove", methods=["POST"])
@login_required
def remove_samples():
    """Remove samples."""
    if current_user.is_admin:
        token = TokenObject(**current_user.get_id())

        sample_ids = json.loads(request.form.get("sample-ids", "[]"))
        if len(sample_ids) > 0:
            result = delete_samples(token, sample_ids=sample_ids)
            current_app.logger.info(
                "removed %d samples, removed from %d groups",
                result["n_deleted"],
                result["removed_from_n_groups"],
            )
    else:
        flash("You dont have permission to remove samples", "warning")
    return redirect(request.referrer)


@samples_bp.route("/samples/cluster/", methods=["GET", "POST"])
@login_required
def cluster(sample_id: str) -> str:
    """Samples view."""
    token = TokenObject(**current_user.get_id())

    if request.method == "POST":
        samples_info = request.body["samples"]
        cgmlst_cluster_samples(token, samples=samples_info)
    return render_template("sample.html", sample_id=sample_id)


@samples_bp.route("/sample/<sample_id>")
@login_required
def sample(sample_id: str) -> str:
    """Generate sample page.

    :param sample_id: Sample id
    :type sample_id: str
    :raises ValueError: _description_
    :raises ValueError: _description_
    :return: Rendered HTML page
    :rtype: str
    """
    current_app.logger.debug("Removing non-validated genes from input")
    token = TokenObject(**current_user.get_id())
    # get sample
    try:
        sample_info = get_sample_by_id(token, sample_id=sample_id)
    except HTTPError as error:
        # throw proper error page
        abort(error.response.status_code)

    # if verbose output should be rendered
    extended = bool(request.args.get("extended", False))

    # if a sample was accessed from a group it can pass the group_id as parameter
    group_id: str | None = request.args.get("group_id")

    # sort phenotypic predictions so Tb is first
    order = {"tbprofiler": 10, "mykrobe": 1}
    sample_info["element_type_result"] = sorted(
        sample_info["element_type_result"],
        key=lambda res: order.get(res["software"], 0),
        reverse=True,
    )

    # filter tbprofiler results and sort variants
    LOG.warning(len(sample_info["element_type_result"][0]["result"]["variants"]))
    sample_info = filter_variants_if_processed(sample_info)
    LOG.warning(len(sample_info["element_type_result"][0]["result"]["variants"]))
    sample_info = sort_variants(sample_info)
    LOG.warning(len(sample_info["element_type_result"][0]["result"]["variants"]))

    # get all actions if sample fail qc
    bad_qc_actions = [member.value for member in BadSampleQualityAction]

    kw_meta_records, meta_tbls = split_metadata(sample_info)

    return render_template(
        "sample.html",
        sample=sample_info,
        group_id=group_id,
        title=sample_id,
        is_filtered=bool(group_id),
        bad_qc_actions=bad_qc_actions,
        extended=extended,
        kw_metadata=kw_meta_records,
        metadata_tbls=meta_tbls,
        token=token.token,
    )


@samples_bp.route("/sample/<sample_id>/similar", methods=["POST"])
@login_required
def find_similar_samples(sample_id: str) -> Tuple[Dict[str, Any], int]:
    """Find samples that are similar."""
    token = TokenObject(**current_user.get_id())
    limit = request.json.get("limit", 10)
    similarity = request.json.get("similarity", 0.5)
    try:
        resp = find_samples_similar_to_reference(
            token, sample_id=sample_id, limit=limit, similarity=similarity
        )
    except HTTPError as error:
        return {"status": 500, "details": str(error)}, 500
    return resp.model_dump(), 200


@samples_bp.route("/sample/<sample_id>/comment", methods=["POST"])
@login_required
def add_comment(sample_id: str) -> str:
    """Post sample."""
    token = TokenObject(**current_user.get_id())
    # post comment
    data = request.form["comment"]
    try:
        post_comment_to_sample(
            token, sample_id=sample_id, user_name=current_user.username, comment=data
        )
    except HTTPError:
        flash("Error posting commment", "danger")
    return redirect(url_for("samples.sample", sample_id=sample_id))


@samples_bp.route("/sample/<sample_id>/comment/<comment_id>", methods=["POST"])
@login_required
def hide_comment(sample_id: str, comment_id: str) -> str:
    """Hist comment for sample."""
    token = TokenObject(**current_user.get_id())
    # hide comment
    try:
        remove_comment_from_sample(token, sample_id=sample_id, comment_id=comment_id)
    except HTTPError as error:
        flash(str(error), "danger")
    return redirect(url_for("samples.sample", sample_id=sample_id))


@samples_bp.route("/sample/<sample_id>/qc_status", methods=["POST"])
@login_required
def update_qc_classification(sample_id: str) -> str:
    """Update the quality control report of a sample."""
    token = TokenObject(**current_user.get_id())

    # build data to store in db
    result = request.form.get("qc-validation", None)
    if result == QualityControlResult.PASSED.value:
        action = None
        comment = ""
    elif result == QualityControlResult.FAILED.value:
        comment = request.form.get("qc-comment", "")
        action = request.form.get("qc-action", "")
    else:
        raise ValueError(f"Unknown value of qc classification, {result}")

    try:
        update_sample_qc_classification(
            token, sample_id=sample_id, status=result, action=action, comment=comment
        )
    except HTTPError as error:
        flash(str(error), "danger")
    return redirect(url_for("samples.sample", sample_id=sample_id))


@samples_bp.route(
    "/sample/<sample_id>/resistance/variants/download", methods=["GET", "POST"]
)
@login_required
def download_lims(sample_id: str):
    """Download a LIMS compatible file with UTF-8 encoding."""
    # get user auth token
    token = TokenObject(**current_user.get_id())

    # default file name
    fmt = request.args.get("fmt", "tsv")
    today = date.today()
    fallback_fname = request.args.get(
        "filename", f"bonsai-lims-export_{sample_id}_{today.isoformat()}"
    )

    # Fetch from API
    try:
        api_resp = get_lims_export_response(token, sample_id=sample_id, fmt=fmt)
    except HTTPError as error:
        # log errors
        status = error.response.status_code == 401
        if status:
            current_app.logger.warning(
                "LIMS export error - no permissoin %s", current_user.username
            )
            flash("You dont have permission to export the result to LIMS", "warning")
        elif status == 404:
            flash("Sample not found", "warning")
        elif status == 422:
            flash("Export is not supported for this assay", "warning")
        elif status == 501:
            flash("Export not implemented for this assay", "warning")
        else:
            current_app.logger.error(
                "LIMS export error - generic error: %s", error.response
            )
            flash("Error when generating export file", "warning")
        return redirect(request.referrer)

    # build Flask response using the API headers and bytes
    content = api_resp.content # bytes
    response = make_response(content)

    # Forward content type if provided
    content_type = api_resp.headers.get("Content-Type")
    if content_type:
        response.headers["Content-Type"] = content_type
    else:
        # fallback based on format
        response.headers["Content-Type"] = (
            "text/tab-separated-values; charset=utf-8" if fmt == "tsv" else "text/csv; charset=utf-8"
        )
    # Forward filename if provided; else build default one
    dispo = api_resp.headers.get("Content-Disposition")
    if not dispo:
        response.headers["Content-Disposition"] = f"attachment; filename={fallback_fname}.txt"
    else:
        response.headers["Content-Disposition"] = dispo
    # Saftey
    response.headers.setdefault("X-Content-Type-Options", "nosniff")
    return response


@samples_bp.route("/sample/<sample_id>/resistance/variants", methods=["GET", "POST"])
@login_required
def resistance_variants(sample_id: str) -> str:
    """Samples view."""
    token = TokenObject(**current_user.get_id())
    sample_info = get_sample_by_id(token, sample_id=sample_id)
    sample_info = sort_variants(sample_info)

    # check if IGV should be enabled
    display_genome_browser = all(
        [

frontend/bonsai_app/blueprints/sample/templates/metadata.html
{% extends "layout.html" %}
{% from "sidebar.html" import sidebar, table_of_content with context %}
{% from "cards.html" import sample_header %}
{% from "metadata_table.html" import meta_table with context %}

{% block css %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('samples.static', filename='sample.css')}}">
{% endblock css %}

{% block content %}
<div class="d-md-none d-sm-block sticky-top bg-secondary">
    <div class="d-flex justify-content-between">
        <button class="btn btn-link fs-2 text-white text-decoration-none"
                type="button" data-bs-toggle="collapse" data-bs-target="#sample-sidebar" 
                aria-expanded="false" aria-controls="sample-sidebar">
            <i class="bi bi-list"></i>
        </button>
        <button class="btn btn-link fs-2 text-white"
                type="button" data-bs-toggle="collapse" data-bs-target="#toc-contents" 
                aria-expanded="false" aria-controls="toc-contents">
            <i class="bi bi-three-dots"></i>
        </button>
    </div>
</div>
<div class="container-fluid br-layout">
    {{ sidebar(sample, bad_qc_actions, metadata=metadata_tbls) }}
    <main class="container-fluid">
        {{ sample_header(sample) }}
        <div class="container-fluid">
            {% set categories=(kw_tbl | list  + grouped_metadata_tbls | list) | unique %}
            {% for category in categories %}
                <h5>{{ category }}</h5>
                <hr class="mt-2 col-md-3 border border-success border-2">
                <div class="row justify-content-md-center">
                    {% if category in kw_tbl %}
                        <div class="col-md-auto w-50">
                            {{ meta_table(kw_tbl[category], 'kw-meta', show_columns=False) }}
                        </div>
                    {% endif %}
                    {% if category in metadata_tbls %}
                        <div class="row justify-content-md-center">
                            {% for meta in grouped_metadata_tbls[category] %}
                                <div class="col-md-auto w-50">{{ meta_table(meta, loop.index, name=meta.fieldname) }}</div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </main>
</div>
{% endblock content %}

frontend/bonsai_app/blueprints/sample/templates/metadata_table.html
{% extends "layout.html" %}

{% block css %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('samples.static', filename='sample.css')}}">
{% endblock css %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('groups.static', filename='datatables.min.js') }}"></script>
{% endblock scripts %}

{% macro meta_table(entry, id, name=None, caption=None, show_columns=True) %}
    <div class="card">
        {% if name %}
            <div class="card-header">{{ entry.fieldname }}</div>
        {% endif %}
        <div class="card-body">
            <div class="table-responsive">
                {% if caption %}
                    <caption>{{ caption }}</caption>
                {% endif %}
                <table id="{{id}}" class="table table-hover">
                    {% if show_columns %}
                        <thead>
                            {% if entry.index | length == entry.data | length %}
                                <th></th>
                            {% endif %}
                            {% for col_name in entry.columns %}
                                <th>{{ col_name }}</td>
                            {% endfor %}
                        </thead>
                    {% endif %}
                    <tbody>
                        {% for row in entry.data %}
                            {% set index=loop.index0 %}
                            <tr>
                                {% for cell_value in row %}
                                    {% if entry.index | length == entry.data | length %}
                                        <th>{{ entry.index[index] }}</th>
                                    {% endif %}
                                    <td>{{ cell_value }}</td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endmacro %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            {% if table %}
                {{ meta_table(table, id='meta-tbl', caption=table.fieldname) }}
            {% endif %}
        </div>
    </div>
</div>
<script>
    const table = new DataTable('#meta-tbl', {
        paging: false, info: false, searching: false, scrollX: false,
        layout: {
            topStart: {
                buttons: ['copyHtml5', 'excelHtml5', 'csvHtml5']
            }
        }
    })
</script>
{% endblock content %}

frontend/bonsai_app/blueprints/sample/templates/resistance_genes.html
{% extends "layout.html" %}
{% from "sidebar.html" import sidebar, sidebar_header %}
{% from "cards.html" import sample_header, virulence_card, fmt_resistance_info %}
{% from "cards.html" import amr_prediction_card with context %}

{% macro export_btn() %}
    {{ sidebar_header("Action") }}
    <form action="{{ url_for('samples.download_lims', sample_id=sample.sample_id) }}">
        <button class="btn btn-sm btn-warning ms-2" type="submit">
            <i class="bi bi-box-arrow-up"></i>
            Export to LIMS
        </button>
    </form>
{% endmacro %}

{% block css %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('samples.static', filename='sample.css')}}">
{% endblock css %}

<form method="POST" action="{{ url_for(request.endpoint, **request.view_args) }}">
    <input value="{{ request.form.get('input-name') }}">
</form>

{% block content %}
{% set footnotes = [] %}
<div class="container-fluid br-layout">
    {{ sidebar(sample, optional_macro=export_btn) }}
    <main class="br-main order-1">
        <div class="br-toc">
            {# right handed sidebar for filters and classification #}
        </div>
        {{ sample_header(sample, class_names="") }}
        <div class="br-content container-fluid pb-5">
            <h5>Resistance prediction</h5>
            <hr class="mt-2 col-md-3 border border-success border-2">
            {{ sample }}
        </div>
    </main>
</div>
<script>
    $(document).ready(() => { 
        // ready select2
        $("#antibiotic-group").select2()
        $("#filter-genes").select2()
        // 
        $("#accept-variant-btn").click(() => {
            // disable rejection reason
            $("#rejection-reason-group").prop('disabled', true)
            // enable antibiotic resistance annotation
            $("#antibiotic-group").prop('disabled', false)
            $("#high-res-btn").prop('disabled', false)
            $("#low-res-btn").prop('disabled', false)
        })
        $("#reject-variant-btn").click(() => {
            // enable rejection reason
            $("#rejection-reason-group").prop('disabled', false)
            // disable antibiotic resistance annotation
            $("#antibiotic-group").prop('disabled', true)
            $("#high-res-btn").prop('disabled', true)
            $("#low-res-btn").prop('disabled', true)
        })
    })
    window.addEventListener("load", () => {
        // reset selected variants on page load and reload
        checkedVariants = Array.from(
            document.querySelectorAll('.br-content input[type="checkbox"]')
            ).filter(input => input.checked).map(input => input.id)
        window.localStorage.setItem("selectedVariants", JSON.stringify(checkedVariants))
    })

    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))

    const selectVariant = (element) => {
        let selectedVariants
        // get selected variants
        if (window.localStorage.getItem("selectedVariants")) {
            selectedVariants = new Set(JSON.parse(localStorage.getItem("selectedVariants")))
        } else {
            selectedVariants = new Set([])
        }
        // update selected variants
        if ( element.checked ) {
            selectedVariants.add(element.name)
        } else {
            selectedVariants.delete(element.name)
        }
        // update selected variant counter
        document.getElementById("selected-variants-counter").innerHTML = selectedVariants.size
        const variantsObj = JSON.stringify(Array.from(selectedVariants))
        document.getElementById("variant-ids-input").value = variantsObj // store the selected variants
        window.localStorage.setItem("selectedVariants", variantsObj)
    }
    // reset selected varants on page load
</script>
{% endblock content %}

frontend/bonsai_app/blueprints/sample/templates/samples.html
{% extends "layout.html" %}

{% block content %}
<h1>Samples page</h1>
<p>Information...</p>
{% endblock content %}

frontend/bonsai_app/blueprints/sample/templates/sidebar.html
{% macro comment_area(sample) %}
<div id="comment-container" class="overflow-auto">
    {% if sample.comments | length > 0 %}
        {% for comment in sample.comments %}
            {% if comment.displayed %}
            <div class="comment-box m-2 p-1 bg-white shadow-sm rounded">
                <form action={{ url_for('samples.hide_comment', sample_id=sample.sample_id, comment_id=comment.id) }} method="POST">
                    <button class="float-end float-top btn btn-sm btn-link text-success" aria-label="Remove" type="submit"><i class="bi bi-trash3"></i></button>
                </form>
                <p class="ps-2 text-sm text-break fw-light">{{ comment.comment }}</p>
                <span class="text-sm text-muted">- {{ comment.username }}, {{ comment.created_at | strftime }}</span>
            </div>
            {% endif %}
        {% endfor %}
    {% else %}
        <p class="text-muted">No comment</p>
    {% endif %}
</div>
<form class="pb-2"
      action={{ url_for('samples.add_comment', sample_id=sample.sample_id) }} method="post">
    <div class="form-floating mt-4">
        <textarea class="form-control" name="comment" id="comment-box" placeholder="Leave a comment" required></textarea>
        <label class="text-muted" for="comment-box">My comment</label>
    </div>
    <button type="submit" class="btn btn-sm btn-outline-success mt-2"> 
        <i class="bi bi-chat-square-text"></i>
        Add comment
    </button>
</form>
{% endmacro %}

{% macro qc_classification_form_fields(bad_qc_actions, selected_qc_status, selected_action, comment_text) %}
    {#

        Form fields for setting QC status.

        Inputs:
        - bad_qc_actions:       List[str]   List of selectable follow-up actions for failed samples
        - selected_qc_status:   str | None  Sample QC status used for pre-selecting QC checkbox.
        - selected_action:      str | None  Selected follow-up action for failed samples.
        - comment_text:         str | None  Comment text.

    #}
    <fieldset id="qc-form-fields">
        <div class="row">
            <div
                class="btn-group btn-group-sm col-auto pb-1"
                role="group"
                aria-label="Sample qc rejection group">
                <input
                    type="radio" class="btn-check btn-sm" name="qc-validation"
                    id="passed-qc-btn" autocomplete="off" value="passed"
                    {% if selected_qc_status == "passed" %}checked{% endif %}
                >
                <label class="btn btn-outline-success" for="passed-qc-btn"><i class="bi bi-hand-thumbs-up"></i></label>
                <input type="radio" class="btn-check btn-sm" name="qc-validation"
                       id="failed-qc-btn" autocomplete="off" value="failed"
                       {% if selected_qc_status == "failed" %}checked{% endif %}
                >
                <label class="btn btn-outline-danger" for="failed-qc-btn"><i class="bi bi-hand-thumbs-down"></i></label>
            </div>
            <div class="col-auto d-flex flex-row">
                <select
                    id="failed-qc-action"
                    class="form-select form-select-sm"
                    name="qc-action"
                    aria-label="Action on failed sample"
                    {% if selected_qc_status != "failed" %}
                    disabled
                    hidden
                    {% endif  %}
                >
                    <option
                        value=""
                        selected
                        disabled
                    >
                        Select action
                    </option>
                    {% for action in bad_qc_actions %}
                    <option
                        value="{{action}}"
                        {% if selected_action == action %}selected{% endif %}
                    >{{action | capitalize}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div id="failed-qc-comment-container" class="row" {% if selected_qc_status != "failed" %}hidden{% endif %}>
            <div class="col-auto pb-1">
                <label class="text-muted" for="failed-qc-comment">Comment</label>
                <textarea type="text" class="form-control" name="qc-comment" id="failed-qc-comment"
                >{{comment_text}}</textarea>
            </div>
        </div>
        <div class="row">
            <div class="col-auto">
                <button
                    id="qc-submit-btn"
                    class="btn btn-sm btn-outline-secondary"
                    disabled
                >Confirm</button>
            </div>
        </div>
    </fieldset>
{% endmacro %}

{% macro qc_form_controls_js() %}
    {#

       JS enhancements for QC form controls.

        - Reset controls when toggling QC status in QC form
        - Disable/enable form submit btn based on input validation

    #}

    // When passing samples:
    document.getElementById("passed-qc-btn").addEventListener("click", (e) => {
        // Clear QC-fail fields
        const select = document.getElementById("failed-qc-action")
        select.disabled = true
        select.hidden = true
        select.value = "0"
        const textArea = document.getElementById("failed-qc-comment-container")
        textArea.hidden = true
    })

    // When failing samples:
    document.getElementById("failed-qc-btn").addEventListener("click", (e) => {
        // Enable selections of actions to take after rejecting a sample:
        const select = document.getElementById("failed-qc-action")
        select.disabled = false
        select.hidden = false
        const textArea = document.getElementById("failed-qc-comment-container")
        textArea.hidden = false
     })

    //On any change in the form:
    document.getElementById("qc-form-fields").addEventListener("change", (e) => {
        // Force followup action selection when failing samples by disabling submit btn:
        const qc_status = document.querySelector("input[name='qc-validation']:checked").value
        const select = document.getElementById("failed-qc-action")
        const submitButton = document.getElementById("qc-submit-btn")

        if (select.value === '' && qc_status === "failed") {
            submitButton.disabled = true;
        } else {
            submitButton.disabled = false;
        }
    })

{% endmacro %}


{% macro qc_classification(sample_qc_classification_obj, bad_qc_actions, sample_id) %}
    {#

        Sidebar UI section for setting QC status in sample-view sidebar

        Inputs:
        - qc_classification_obj     SampleQcClassification  Sample QC settings
        - bad_qc_actions:           List[str]               List of selectable follow-up actions for failed samples
        - sample_id:                str                     Current sample id

    #}
    <form id="qc-classification-form" name="qc-classification" class="form-control">
        {{ qc_classification_form_fields(
        bad_qc_actions=bad_qc_actions,
        selected_qc_status=sample_qc_classification_obj.status,
        selected_action=sample_qc_classification_obj.action,
        comment_text=sample_qc_classification_obj.comment
        ) }}
    </form>
{% endmacro %}

{% macro metadata_link(endpoint, sample_id, entry) %}
    {% if request.endpoint.endswith(endpoint) %}
        {% set selected="active" %}
    {% else %}
        {% set selected="" %}
    {% endif %}
    <li class="nav-item mb-2 {{ selected }}">
        <a class="link-secondary link-underline-success" href="{{ url_for(endpoint, sample_id=sample_id, fieldname=entry.fieldname) }}">
            <i class="bi bi-table"></i>
            {{ entry.fieldname }}
        </a>
    </li>
{% endmacro %}

{% macro report_link(endpoint, name, sample_id, icon="bi-file-earmark-text") %}
    {% if request.endpoint.endswith(endpoint) %}
        {% set selected="active" %}
    {% else %}
        {% set selected="" %}
    {% endif %}
    <li class="nav-item mb-2 {{ selected }}">
        <a class="link-secondary link-underline-success" 
            href={{ url_for(endpoint, sample_id=sample_id) }}>
            <i class="bi {{ icon }}"></i>
            {{ name }}
        </a>
    </li>
{% endmacro %}

{% macro sidebar_header(text, size="sm", class_names="mt-1 mb-1 ") %}
    {% if size == "md" %}
        {% set header_size="sidebar-heading-md" %}
    {% else %}
        {% set header_size="sidebar-heading-sm" %}
    {% endif %}
    <h6 class="{{ header_size }} text-muted text-uppercase {{ class_names }}">{{text}}</h6>
{% endmacro %}

{% macro sidebar(sample, bad_qc_actions, metadata=[], optional_macro=None) %}
<aside class="br-sidebar border-end pe-2">
    <div>
        {{ sidebar_header("Metadata")}}
        <ul class="nav flex-column">
            {% for meta in metadata %}
                {{ metadata_link('samples.open_metadata_tbl', sample_id=sample.sample_id, entry=meta) }}
            {% endfor %}
        </ul>
        {{ sidebar_header("Reports")}}
        <ul class="nav flex-column">
            {{ report_link('samples.metadata', sample_id=sample.sample_id, name='Metadata', icon="bi-clipboard-data") }}
            {{ report_link('samples.sample', sample_id=sample.sample_id, name='Summary') }}
            {{ report_link('samples.resistance_variants', sample_id=sample.sample_id, name='Variants') }}
        </ul>

        {{ sidebar_header("Quality control")}}
        {{ qc_classification(sample.qc_status, bad_qc_actions, sample.sample_id) }}

        {# optional specific to certain views #}
        {% if optional_macro %}
            {{ optional_macro() }}
        {% endif %}

        {# comment area #}
        {{ sidebar_header("Comments")}}
        {{ comment_area(sample) }}
    </div>
</aside>
<script>
    function removeComment(btn) {
        // remove comment from sample
        const apiUrl = "{{ config.API_EXTERNAL_URL }}"
        fetch(`${apiURL}/samples/basket/add`, {
        }).then(response => {
            btn.parentElement.remove()
        })
    }
</script>
{% endmacro %}


{% macro table_of_content() %}
<div class="br-toc y-lg-0 px-sm-1 text-body-secondary">
    {{ sidebar_header("On this page") }}
    <hr class="d-none d-md-block my-2 ms-3">
    <div id="toc-contents" class="collapse d-md-block">
        <ul class="nav nav-flush flex-column mb-auto text-left">
            <li class="nav-item">
                <a class="nav-link" href="#sample-id-heading">ID</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#epi-typing-heading">Typing</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#phenotype-heading">Phenotype</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#virulence-heading">Virulence</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#qc-heading">QC</a>
            </li>
        </nav>
    </div>
</div>
{% endmacro %}