frontend/bonsai_app/blueprints/groups/views.py
"""Declaration of views for groups"""

import json
import logging
from urllib.parse import urlparse

from bonsai_app.bonsai import (TokenObject, create_group, delete_group,
                               get_group_by_id, get_groups, get_samples,
                               get_samples_in_group, get_valid_group_columns,
                               update_group, update_sample_qc_classification)
from bonsai_app.models import (BadSampleQualityAction, PhenotypeType,
                               QualityControlResult)
from flask import (Blueprint, abort, flash, redirect, render_template, request,
                   url_for)
from flask_login import current_user, login_required
from requests.exceptions import HTTPError

from .controller import format_tablular_data

LOG = logging.getLogger(__name__)

groups_bp = Blueprint(
    "groups",
    __name__,
    template_folder="templates",
    static_folder="static",
    static_url_path="/groups/static",
)


@groups_bp.route("/groups")
@login_required
def groups() -> str:
    """Generate page that displays groups and all samples.

    :return: generated HTML page
    :rtype: str
    """
    # if not valid token
    if current_user.get_id() is None:
        LOG.info(
            "User not logged in: %s %s", current_user.first_name, current_user.last_name
        )
        return redirect(url_for("public.index"))

    token = TokenObject(**current_user.get_id())
    samples_info = get_samples(token, limit=0, skip=0)

    bad_qc_actions = [member.value for member in BadSampleQualityAction]

    # generate table data
    col_def = get_valid_group_columns(token)
    table_data = format_tablular_data(samples_info["data"], col_def)

    return render_template(
        "groups.html",
        title="Groups",
        table_data=table_data,
        token=current_user.get_id().get("token"),
        bad_qc_actions=bad_qc_actions,
    )


@groups_bp.route("/groups/edit", methods=["GET", "POST"])
@groups_bp.route("/groups/edit/<group_id>", methods=["GET", "POST"])
@login_required
def edit_groups(group_id: str | None = None):
    """Generate edit groups view

    :param group_id: Group id, defaults to None
    :type group_id: str, optional
    :return: generated HTML page
    :rtype: str
    """
    # if not valid token or if user is not admin
    if current_user.get_id() is None or not current_user.is_admin:
        return redirect(url_for("public.index"))

    token = TokenObject(**current_user.get_id())
    all_groups = get_groups(token)

    # remove group from database
    if request.method == "POST":
        # if a group should be removed
        if "input-remove-group" in request.form:
            try:
                delete_group(token, group_id=request.form.get("input-remove-group"))
                flash("Group updated", "success")
            except HTTPError as err:
                flash(f"An error occurred when updating group, {err}", "danger")
            return redirect(url_for("groups.edit_groups"))
        elif "input-update-group" in request.form:
            updated_data = json.loads(request.form.get("input-update-group"))
            try:
                update_group(token, group_id=group_id, data=updated_data)
                flash("Group updated", "success")
                return redirect(url_for("groups.edit_groups", group_id=group_id))
            except HTTPError as err:
                flash(f"An error occurred when updating group, {err}", "danger")
        elif "input-create-group" in request.form:
            input_data = json.loads(request.form.get("input-create-group", {}))
            try:
                group_id = input_data["group_id"]
                create_group(token, data=input_data)
                flash("Group updated", "success")
                return redirect(url_for("groups.edit_groups", group_id=group_id))
            except HTTPError as err:
                flash(f"An error occurred when updating group, {err}", "danger")

    # get valid phenotypes
    valid_phenotypes = {
        entry.name.lower().capitalize().replace("_", " "): entry.value
        for entry in PhenotypeType.__members__.values()
    }
    # get valid columns and set used cols as checked
    all_group_ids = [group["group_id"] for group in all_groups]
    if group_id is not None and group_id in all_group_ids:
        selected_group = next(
            iter(group for group in all_groups if group["group_id"] == group_id)
        )
        cols_in_group = selected_group["table_columns"]
    else:
        cols_in_group = []

    # annotate if column previously have been selected
    valid_cols_idx = {
        col["id"]: col for col in get_valid_group_columns(token_obj=token)
    }
    for col in cols_in_group:
        col_id = col["id"]
        valid_cols_idx[col_id]["selected"] = True
        for key in ["sortable", "searchable", "visible"]:
            valid_cols_idx[col_id][key] = col[key]

    return render_template(
        "edit_groups.html",
        title="Groups",
        selected_group=group_id,
        groups=all_groups,
        valid_columns=list(valid_cols_idx.values()),
        valid_phenotypes=valid_phenotypes,
    )


@groups_bp.route("/groups/<group_id>")
@login_required
def group(group_id: str) -> str:
    """Group view.

    :param group_id: Group id
    :type group_id: str
    :return: html page
    :rtype: str
    """
    # check if qc metrics should be displayed
    display_qc: bool = request.args.get(
        "qc", False, type=lambda val: val.lower() == "true"
    )

    # query API for sample info
    token = TokenObject(**current_user.get_id())
    try:
        samples_info = get_samples_in_group(
            token,
            group_id=group_id,
            prediction_result=not display_qc,
            qc_metrics=display_qc,
        )
        # get column definition to use
        group_info = get_group_by_id(token, group_id=group_id)
    except HTTPError as error:
        # throw proper error page
        abort(error.response.status_code)

    # Pre-select samples in sample table:
    selected_samples = request.args.getlist("samples")

    bad_qc_actions = [member.value for member in BadSampleQualityAction]

    # generate table data
    columns = group_info.get("table_columns", [])
    if len(columns) > 0:
        columns = get_valid_group_columns(token, group_id=group_id)
    else:  # get default columns
        columns = get_valid_group_columns(token)
    table_data = format_tablular_data(samples_info["data"], columns)

    # indicate view in title, used for testing
    title = f"Group - {group_id}"
    if display_qc:
        title += " - QC results"
    return render_template(
        "group.html",
        title=title,
        group_id=group_id,
        group_name=group_info["display_name"],
        bad_qc_actions=bad_qc_actions,
        selected_samples=selected_samples,
        group_desc=group_info["description"],
        table_data=table_data,
        table_definition=group_info["table_columns"],
        modified=group_info["modified_at"],
        display_qc=display_qc,
        token=current_user.get_id().get("token"),
    )


@groups_bp.route("/groups/qc_status", methods=["POST"])
@login_required
def update_qc_classification():
    """Update the quality control report of one or more samples.

    Redirects back to groups.groups and preserves table selection
    """

    selected_samples = request.form.getlist("qc-selected-samples")

    LOG.debug("Processing request to set QC for %s", selected_samples)

    if not selected_samples:
        LOG.warning("Received request to set QC but no selected samples")
        flash(
            "No samples selected for QC status update. Please choose at least one sample.",
            "warning",
        )

    token = TokenObject(**current_user.get_id())

    # build data to store in db
    result = request.form.get("qc-validation", None)
    if result == QualityControlResult.PASSED.value:
        action = None
        comment = ""
    elif result == QualityControlResult.FAILED.value:
        comment = request.form.get("qc-comment", "")
        action = request.form.get("qc-action", "")
    else:
        raise ValueError(f"Unknown value of qc classification, {result}")

    for sample_id in selected_samples:
        try:
            update_sample_qc_classification(
                token,
                sample_id=sample_id,
                status=result,
                action=action,
                comment=comment,
            )
        except Exception as error:
            LOG.exception(
                "Encountered error when updating QC status for sample %s:", sample_id
            )
            flash(str(error), "danger")

    # add sample ids as params to referrer url
    url = urlparse(request.referrer)
    sample_id_param = "&".join([f"samples={sid}" for sid in selected_samples])
    upd_url = url._replace(query=sample_id_param).geturl()
    return redirect(upd_url)

frontend/bonsai_app/blueprints/groups/templates/cell_fmt.html
{% macro sample_btn_renderer(cell_info)  %}
    <td>
        {% set params={"sample_id": cell_info} %}
        {% if group_id is defined %}
            {% do params.update({"group_id": group_id}) %}
        {% endif %}
        <a href="{{ url_for('samples.sample', **params) }}">Open</a>
    </td>
{% endmacro %}

{% macro taxonomic_name_renderer(cell_info) %}
    <td>
        <span class="fw-light fst-italic">{{ cell_info }}</span>
    </td>
{% endmacro %}

{% macro qc_status_renderer(cell_info) %}
    {% set status = cell_info.status %}
    {% if status == 'passed' %}
        {% set text_colour = 'text-success' %}
    {% elif status == 'failed' %}
        {% set text_colour = 'text-danger' %}
    {% else %}
        {% set text_colour = '' %}
    {% endif %}


    {% if cell_info.action and cell_info.comment %}
        {% set action = 'Action: ' + cell_info.action %}
        {% set tooltip_info = action + ' - ' + cell_info.comment %}
    {% elif cell_info.action %}
        {% set tooltip_info = cell_info.action %}
    {% elif cell_info.comment %}
        {% set tooltip_info = cell_info.comment %}
    {% else %}
        {% set tooltip_info = None %}
    {% endif %}
    <td>
        <span class="fw-light {{ text_colour }}">
            {{ status }}
        </span>
        {% if tooltip_info %}
            <i class="bi bi-info-circle"
                data-bs-toggle="tooltip" data-bs-placement="top"
                data-bs-title="{{ tooltip_info }}"></i>
        {% endif %}
    </td>
{% endmacro %}

{% macro mrsa_renderer(amr)  %}
    {% set has_meca = amr | has_arg("mecA") %}
    <td>
    {% if has_meca %}
        <span class="bade bg-danger fw-normal text-light fs-6">MRSA</span>
    {% endif %}
    </td>
{% endmacro %}

{% macro mlst_renderer(cell_info) %}
    {% if cell_info.data == None %}
        {% set mlst_st="-" %}
    {% else %}
        {% set mlst_st=cell_info.data %}
    {% endif %}
    <td>
        <span class="fw-normal fs-6">{{mlst_st}}</span>
    </td>
{% endmacro %}

{% macro pvl_renderer(pvl) %}
    {% set pvl_tag = pvl | get_pvl_tag %}
    <td>
        <span class="badge bg-{{pvl_tag.severity}} fw-normal">{{pvl_tag.label}}</span>
    </td>
{% endmacro %}

{% macro tags_renderer(tag_info) %}
    <td data-search="{% for tag in tag_info %}{{tag.label}} {% endfor %}">
    {% for tag in tag_info %}
        <span class="badge text-bg-{{tag.severity}} p-1 me-1"
              data-bs-toggle="tooltip" data-bs-placement="top" 
              data-bs-title="{{ tag.description }}">{{tag.label}}</span>
    {% endfor %}
    </td>
{% endmacro %}

{% macro comment_tooltip(comment) %}
<p class='mb-1'>{{ comment.comment }}</p>
<p class='mt-0 text-end fst-italic'>- {{ comment.username }}</p>
<hr>
{% endmacro %}

{% macro comments_renderer(cell_info) %}
    {% set comments_obj = cell_info %}
    <td>
        {% if comments_obj | length %}
            <span class="badge text-bg-primary" data-bs-toggle="tooltip" 
                  data-bs-placement="top" data-bs-html="true"
                  data-bs-title="
                  <div>
                  {% for comment in comments_obj %}
                  {% if comment.displayed %}{{ comment_tooltip(comment) }}{% endif %}
                  {% endfor %}
                  </div>
                  ">
                <i class="bi bi-chat-right"></i>
                <span>{{ comments_obj | length }}</span>
            </span>
        {% endif %}
    </td>
{% endmacro %}

{% macro text_renderer(cell_info) %}
    <td>{{ cell_info }}</td>
{% endmacro %}

{% macro number_renderer(cell_info) %}
    <td>{{ cell_info | fmt_number }}</td>
{% endmacro %}

{% macro date_renderer(cell_info) %}
    <td>{{ cell_info | strftime }}</td>
{% endmacro %}

{% macro boolean_renderer(cell_info) %}
    <td>
        {% if cell_info %}
            <i class="bi bi-check-lg"></i>
        {% else %}
            <i class="bi bi-x"></i>
        {% endif %}
    </td>
{% endmacro %}

{% macro list_renderer(cell_info) %}
    <td>{{ cell_info | join(', ') }}</td>
{% endmacro %}

frontend/bonsai_app/blueprints/groups/templates/group.html
{% extends "layout.html" %}
{% from "shared.html" import search_similar_btn, add_to_basket_btn, qc_bulk_toggle, delete_samples_btn %}
{% from "shared.html" import sample_table with context %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('groups.static', filename='groups.css') }}">
    <link rel="stylesheet" href="{{ url_for('groups.static', filename='datatables.min.css') }}">
{% endblock css %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('groups.static', filename='datatables.min.js') }}"></script>
{% endblock scripts %}

{% block content %}
<div class="card bg-white mt-2 col-lg-auto mx-2">
    <div class="card-body br-main">
        <h4 class="card-title me-auto fw-light">{{group_name}}</h4>
        <hr class="mt-2 col-md-2 border border-success border-2">
        <p class="card-text mb-2">{{group_desc}}</p>
        <table class="table table-sm w-auto">
            <thead><tr><th>Samples</th><th>Updated</th></tr></thead>
            <tbody>
                <tr>
                    <td id="samples-counter">{{ table_data.rows | length }}</td>
                    <td id="group-modified-timestamp">{{ modified | strftime }}</td></tr>
            </tbody>
        </table>
        <nav class="navbar bg-light">
            <div class="container-fluid justify-content-start">
                {{ add_to_basket_btn() }}
                {% if current_user.is_admin %}
                    {{ delete_samples_btn() }}

                    {# remove samples from group #}
                    <button id="remove-from-group-btn" class="btn btn-sm btn-secondary ms-1" data-bi-group-id="{{ group_id }}">
                        <i class="bi bi-folder-minus"></i>
                    </button>

                    {# Dropdown for adding samples to group #}
                    <div id="add-samples-to-group-container"></div>
                {% endif %}
                {{ search_similar_btn() }}
                {% if display_qc %}
                    {{ qc_bulk_toggle(bad_qc_actions)}}
                {% endif %}
                <div class="btn-group ms-2" role="group" aria-label="Three button group">
                    <a type="button"
                            class="btn btn-outline btn-dark btn-sm {% if not display_qc %}active{% endif %}"
                            data-test-id="open-qc-view-btn"
                            data-bs-toggle="tooltip" data-bs-title="Show prediction summary"
                            href="{{ url_for('groups.group', group_id=group_id, qc=False) }}">
                        <i class="bi bi-search"></i>
                    </a>
                    <a type="button" 
                            class="btn btn-outline btn-dark btn-sm {% if display_qc %}active{% endif %}"
                            data-test-id="open-qc-view-btn"
                            data-bs-toggle="tooltip" data-bs-title="Show QC metrics"
                            href="{{ url_for('groups.group', group_id=group_id, qc=True) }}">
                        <i class="bi bi-bar-chart-line"></i>
                    </a>
                </div>
            </div>
        </nav>
        {{ sample_table(table_data) }}
    </div>
</div>
<script>
    const apiUrl = "{{ config.API_EXTERNAL_URL }}"
    const accessToken = "{{ token }}"
    const groupId = "{{ group_id }}"
    // template code for adding to basket
    // template code for searching similar samples

    document.addEventListener('DOMContentLoaded', () => {
        bonsai.initGroupView(groupId, apiUrl, accessToken, "")
    });
</script>
{% endblock content %}

frontend/bonsai_app/blueprints/groups/templates/groups.html
{% extends "layout.html" %}
{% from "shared.html" import search_similar_btn, add_to_basket_btn, qc_bulk_toggle, delete_samples_btn, sample_table %}

{% block css %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('groups.static', filename='groups.css') }}">
<link rel="stylesheet" href="{{ url_for('groups.static', filename='datatables.min.css') }}">
{% endblock css %}

{% block scripts %}
{{ super() }}
{% endblock scripts %}

{% block content %}
<div class="card bg-white mt-2 col-lg-auto mx-2">
    <div class="card-body br-main">
        <h5 class="card-title text-uppercase fw-light">Groups</h5>
        <hr class="mt-2 col-md-2 border border-success border-2">
        <div id="group-container" data-test-id="group-container"></div>
        <h5 class="card-title text-uppercase fw-light pt-4">All samples</h5>
        <hr class="mt-2 col-md-2 border border-success border-2">
        <nav class="navbar bg-light">
            <div id="user-action-container" class="container-fluid justify-content-start">
                {{ add_to_basket_btn() }}

                {% if current_user.is_admin %}
                    {{ delete_samples_btn() }}

                    {# Target for dropdown for adding samples to group #}
                    <div id="add-samples-to-group-container"></div>
                {% endif %}

                {{ search_similar_btn() }}

                {{ qc_bulk_toggle(bad_qc_actions) }}
            </div>
        </nav>
        {{ sample_table(table_data) }}
    </div>
</div>
<script>
    const apiUrl = "{{ config.API_EXTERNAL_URL }}"
    const accessToken = "{{ token }}"
    const groupId = null
    // template code for adding to basket
    // template code for searching similar samples

    document.addEventListener('DOMContentLoaded', () => {
        bonsai.initGroupView(groupId, apiUrl, accessToken, "")
    });
</script>
{% endblock content %}

frontend/bonsai_app/blueprints/groups/templates/shared.html
{% from  'sidebar.html' import qc_classification_form_fields  %}
{% import "cell_fmt.html" as render_funcs with context %}

{% macro add_to_basket_btn() %}
<button id="add-to-basket-btn" class="btn btn-sm btn-outline-success" data-test-id="add-to-basket-btn" disabled>
    <i class="bi bi-plus-lg"></i>
    <span>Add to basket</span>
</button>
{% endmacro %}

{% macro search_similar_btn() %}
<div id="find-similar-dropdown" class="dropdown similar-samples-container">
    <button id="similar-samples-dropdown-btn"
            class="btn btn-sm btn-outline-secondary dropdown-toggle ms-4" 
            data-bs-toggle="dropdown" disabled>
        <span class="content">
            <i class="bi bi-search"></i>
            <span>Find similar</span>
        </span>
        <span class="loading align-middle d-none">
            <span class="spinner-grow text-success spinner-grow-sm" role="status"></span>
            Loading...
        </span>
    </button>
    <div class="dropdown-menu dropdown-menu-end p-2" style="min-width: 300px;">
        <div class="d-flex justify-content-between align-items-center mb-2">
            <h6 class="dropdown-header mb-0">Find Similar Samples</h6>
            <span class="ms-2" data-bs-toggle="tooltip" data-bs-placement="left"
                title="Enter a minimum similarity percentage (0–100). Optionally set a maximum number of results. Click 'Find Similar Samples' to search.">
            <i class="bi bi-info-circle" style="cursor: help;"></i>
            </span>
        </div>
        <form class="needs-validation">
            <div class="mb-2">
                <label for="similar-samples-threshold" class="form-label">Minimum similarity (%)</label>
                <input type="number" min="0" max="1" step="0.01" name="similar-samples-threshold" 
                        id="similar-samples-threshold" class="form-control form-control-sm" 
                        placeholder="Min similarity" value="0.95" required>
                <div id="similar-samples-limit-help" class="form-text">Include samples with similarity above this percentage. Example: 95 = 95%.</div>
            </div>
            <div class="mb-2">
                <label for="similar-samples-limit" class="form-label">Maximum results</label>
                <input type="number" name="similar-samples-limit" 
                        id="similar-samples-limit" class="form-control form-control-sm" 
                        placeholder="Number of samples" value="50" required>
                <div id="similar-samples-limit-help" class="form-text">Limit the number of samples returned.</div>
            </div>
            <button type="button" id="select-similar-samples-btn" class="btn btn-sm btn-outline-success mt-2" >
                <i class="bi bi-search"></i>
                Find similar samples
            </button>
        </form>
    </div>
</div>
{% endmacro %}


{% macro qc_bulk_toggle(bad_qc_actions) %}
    {#

        Button interacting with sample list in groups. Activates pop up dialog when used.

        Inputs:
            - bad_qc_actions : List[str]    List of selectable follow-up actions for failed samples

    #}
    <div id="qc-menu-dropdown" class="dropdown">
        <button
            id="toggle-qc-btn"
            class="btn btn-sm btn-outline-secondary dropdown-toggle ms-4"
            data-bs-toggle="dropdown" data-bs-auto-close="outside"
            disabled
        >
            Set QC status
        </button>
        <form
            class="needs-validation"
            method="post"
            id="qc-form-control"
            action="{{ url_for('groups.update_qc_classification') }}"
        >
            <div id="qc-dropdown-contents" class="dropdown-menu dropdown-menu-end p-2">
                {{ qc_classification_form_fields(
                    bad_qc_actions=bad_qc_actions,
                    selected_qc_status = "",
                    selected_action = "",
                    comment_text = ""
                ) }}
            </div>
        </form>
    </div>
{% endmacro %}

{% macro delete_samples_btn() %}
    <button id="remove-samples-btn" class="btn btn-sm btn-outline-danger ms-1" disabled>
        <i class="bi bi-trash"></i>
        <span>Delete samples</span>
    </button>
{% endmacro %}

{% macro sample_table(table_data) %}
    {# build sample table #}
    <p>Group id inside table: {{ group_id }}</p>
    <table id="sample-table" class="display table table-striped">
        <thead>
            <tr>
                {# build table header #}
                {% for column in table_data.columns %}
                    {% if column.label is not none %}
                        <th 
                            data-orderable="{{ column.sortable | lower }}" data-searchable="{{ column.searchable | lower }}"
                            data-visible="{{ column.visible | lower }}"
                            >
                            {{ column.label }}
                        </th>
                    {% else %}
                        <th></th>
                    {% endif %}
                {% endfor %}
            </th>
        </thead>
        <tbody>
            {% for row in table_data.rows %}
                <tr id="{{ row.sample_id }}" {% if test_id is not none %}data-test-id="sample-row-{{ loop.index }}"{% endif %}>
                    {% for col_info in table_data.columns %}
                        {% set cell_data=row[col_info.id] %}
                        {{ render_funcs[col_info.renderer](cell_data) }}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endmacro %}


{% macro render_cell(cell_info) %}
    {% set style = cell_info.style or '' %}
    {% set tooltip = cell_info.tooltip or '' %}
    {% set link = cell_info.link %}
    {% set data = cell_info.data %}
    {% set macro = cell_info.render_macro %}

    {% if cell_info.type == "list" %}
        {% set data = data | join(', ') %}
    {% elif cell_info.type == "number" %}
        {% set data = data | fmt_number %}
    {% endif %}

    {% if macro %}
        {{ render_funcs[macro](cell_info) }}
    {% else %}
        <td class="{{ style }}" 
            {% if tooltip %}
                data-bs-toggle="tooltip" data-bs-placement="top"
                data-bs-title="{{ cell_info.tooltip }}">
            {% endif %}
        >
            {{ data }}
        </td>
    {% endif %}
{% endmacro %}